import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import React, { StrictMode } from "react";
// import { createRoot } from "react-dom/client";
import "./styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
